# Generated by Django 5.0 on 2023-12-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='idea',
            field=models.TextField(default='/'),
            preserve_default=False,
        ),
    ]
