# Generated by Django 5.0 on 2024-01-04 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('intro', models.TextField(null=True)),
                ('date', models.DateField(null=True)),
                ('subtitle_1', models.TextField(null=True)),
                ('text_1', models.TextField(null=True)),
                ('subtitle_2', models.TextField(null=True)),
                ('text_2', models.TextField(null=True)),
                ('subtitle_3', models.TextField(null=True)),
                ('text_3', models.TextField(null=True)),
                ('cta_title', models.TextField(null=True)),
                ('cta_text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudioComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('audio', models.FileField(upload_to='')),
                ('skript', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('account_link', models.CharField(blank=True, max_length=511, null=True)),
                ('password', models.CharField(max_length=255)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
            ],
        ),
        migrations.CreateModel(
            name='SpreadshirtDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='idea',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='idea',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='igpost',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='igslide',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.post'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='post_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='IGPost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.igpost'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.video'),
        ),
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.topic'),
        ),
        migrations.AlterField(
            model_name='reason',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.article'),
        ),
        migrations.AddField(
            model_name='post',
            name='audio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.audiocomment'),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('socialmedia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.socialmedia')),
                ('access_token', models.CharField(blank=True, max_length=511, null=True)),
                ('account_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('core.socialmedia',),
        ),
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('socialmedia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.socialmedia')),
                ('access_token', models.CharField(blank=True, max_length=511, null=True)),
                ('account_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('core.socialmedia',),
        ),
        migrations.CreateModel(
            name='Pinterest',
            fields=[
                ('socialmedia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.socialmedia')),
                ('access_token', models.CharField(blank=True, max_length=511, null=True)),
                ('account_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('core.socialmedia',),
        ),
        migrations.CreateModel(
            name='Wordpress',
            fields=[
                ('socialmedia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.socialmedia')),
            ],
            bases=('core.socialmedia',),
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('socialmedia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.socialmedia')),
                ('access_token', models.CharField(blank=True, max_length=511, null=True)),
                ('account_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('core.socialmedia',),
        ),
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='core.hashtag'),
        ),
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='core.keyword'),
        ),
        migrations.CreateModel(
            name='LongVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('videoPath', models.CharField(max_length=255)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.audiocomment')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='LongVideo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.longvideo'),
        ),
        migrations.AddField(
            model_name='post',
            name='mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mode'),
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='music')),
                ('mode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mode')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='postType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.posttype'),
        ),
        migrations.AddField(
            model_name='post',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
        migrations.CreateModel(
            name='BackgroundVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='backgrounf_video')),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.theme')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.theme'),
        ),
        migrations.AddField(
            model_name='project',
            name='facebook_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.facebook'),
        ),
        migrations.AddField(
            model_name='project',
            name='instagram_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.instagram'),
        ),
        migrations.AddField(
            model_name='project',
            name='pinterest_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pinterest'),
        ),
        migrations.AddField(
            model_name='project',
            name='wordpress_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.wordpress'),
        ),
        migrations.AddField(
            model_name='project',
            name='youtube_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.youtube'),
        ),
        migrations.CreateModel(
            name='FacebookPublication',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.publication')),
                ('facebook_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.facebook')),
            ],
            bases=('core.publication',),
        ),
        migrations.AddField(
            model_name='post',
            name='facebook_publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.facebookpublication'),
        ),
        migrations.CreateModel(
            name='InstagramPublication',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.publication')),
                ('instagram_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.instagram')),
            ],
            bases=('core.publication',),
        ),
        migrations.AddField(
            model_name='post',
            name='instagram_publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.instagrampublication'),
        ),
        migrations.CreateModel(
            name='PinterestPublication',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.publication')),
                ('pinterest_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pinterest')),
            ],
            bases=('core.publication',),
        ),
        migrations.AddField(
            model_name='post',
            name='pinterest_publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pinterestpublication'),
        ),
        migrations.CreateModel(
            name='WordpressPublication',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.publication')),
                ('wordpress_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.wordpress')),
            ],
            bases=('core.publication',),
        ),
        migrations.AddField(
            model_name='post',
            name='wordpress_publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.wordpresspublication'),
        ),
        migrations.CreateModel(
            name='YoutubePublication',
            fields=[
                ('publication_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.publication')),
                ('youtube_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.youtube')),
            ],
            bases=('core.publication',),
        ),
        migrations.AddField(
            model_name='post',
            name='youtube_publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.youtubepublication'),
        ),
    ]
