# Generated by Django 5.0 on 2023-12-20 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_idea_idea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.post'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='post_created',
            field=models.DateTimeField(null=True),
        ),
    ]
