# Generated by Django 5.0 on 2024-01-04 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_backgroundimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postType',
            new_name='post_type',
        ),
    ]
