# Generated by Django 5.0 on 2024-01-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_posttype_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='watermark',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
