# Generated by Django 5.0 on 2024-01-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_watermark'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slide_mask_first',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='slide_mask_last',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='slide_mask_regular',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
