# Generated by Django 5.0 on 2024-01-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_slide_mask_first_project_slide_mask_last_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mode',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
