# Generated by Django 5.0 on 2024-01-04 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_post_mode_alter_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mode'),
        ),
    ]
